### PR TITLE
Changed database to PostgreSQL

### PR DESCRIPTION
**Pull request by greenled**
This changes the main DBMS from MongoDB to PostgreSQL

### CODE REVIEW

**Comment by greenled** [comment]
@rickmclean I enabled [Review Apps](https://devcenter.heroku.com/articles/github-integration-review-apps) for this repo in Heroku. See the temp app spawed at https://thunderbit-pr-30.herokuapp.com/. What a great idea from Heroku!

**Comment by greenled** [comment]
Now we can safely and easily test PRs in a prodduction-like env.

**Comment by greenled** [comment]
Now we can safely and easily test PRs in a prodduction-like env.

**Comment by greenled** [comment]
@rickmclean Please review this one, I have made major changes. Feel free to merge and close it.

**Comment by rickmclean** [comment]
This works fine. Merging... merged!

**Pull request merged**
