### PR TITLE
Tagging

### PR DESCRIPTION
**Pull request by greenled**
So, more tags. Now in the items list. Please don't merge this ;)

### CODE REVIEW

**Comment by greenled** [comment]
This PR is a continuation of #20 Please comment here about the new tags feature

**Comment by greenled** [comment]
@rickmclean do you think the upload form should be cleaned after clicking the Cancel button?

**Comment by rickmclean** [comment]
I won't merge this, don't worry!

**Comment by rickmclean** [comment]
I guess that would be the normal behavior, in most of the software systems
when the Cancel button is clicked everything is reset to default.

**Comment by greenled** [comment]
Yeah, that sounds reasonable. I'll clean it on Cancel

**Pull request merged**
