### PR TITLE
Tagging

### PR DESCRIPTION
**Pull request by greenled**
@rickmclean check this out. We are gonna have tags, finally! Try this and see the tag cloud on the upload form. Tell me what do you think.

### CODE REVIEW

**Comment by rickmclean** [comment]
OK!

**Comment by greenled** [comment]
Oops...didn't mention this should not be merged yet :smile: . I still have to add tags to the items list. Will keep pushing to this branch and merge again later.

**Comment by rickmclean** [comment]
I think there is a bug because when I add some tags and click the Cancel
button, and then I click the "Add file" button again the tags already
added before continue to show.

**Comment by greenled** [comment]
No, it's ok. I meant it to be that way so you can go back and forth without loosing the form's content.

**Comment by greenled** [comment]
See #21 for more on tagging and send comments there please

**Pull request merged**
