### PR TITLE
Changed thunderbit heroku HTTP URL

### PR DESCRIPTION
**Pull request by zloster**
Changed thunderbit heroku HTTP URL to: http://thunderbit.herokuapp.com.

Here is my DNS query log:

```
X@Y:~$ dig thunderbit.herokuapp.com

; <<>> DiG 9.9.5-3ubuntu0.7-Ubuntu <<>> thunderbit.herokuapp.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47148
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;thunderbit.herokuapp.com.      IN      A

;; ANSWER SECTION:
thunderbit.herokuapp.com. 60    IN      A       46.137.183.180

;; AUTHORITY SECTION:
herokuapp.com.          578     IN      NS      ns-662.awsdns-18.net.
herokuapp.com.          578     IN      NS      ns-505.awsdns-63.com.
herokuapp.com.          578     IN      NS      ns-1624.awsdns-11.co.uk.
herokuapp.com.          578     IN      NS      ns-1378.awsdns-44.org.

;; ADDITIONAL SECTION:
ns-505.awsdns-63.com.   6939    IN      A       205.251.193.249
ns-662.awsdns-18.net.   166265  IN      A       205.251.194.150
ns-1378.awsdns-44.org.  166272  IN      A       205.251.197.98
ns-1624.awsdns-11.co.uk. 166272 IN      A       205.251.198.88

;; Query time: 37 msec
;; SERVER: XXX.XXX.XXX.XXX#53(XXX.XXX.XXX.XXX)
;; WHEN: Mon Feb 08 20:36:26 EET 2016
;; MSG SIZE  rcvd: 270

X@Y:~$ dig thunderbit.heroku-app.com

; <<>> DiG 9.9.5-3ubuntu0.7-Ubuntu <<>> thunderbit.heroku-app.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54453
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;thunderbit.heroku-app.com.     IN      A

;; ANSWER SECTION:
thunderbit.heroku-app.com. 488  IN      A       5.39.99.50

;; Query time: 4 msec
;; SERVER: XXX.XXX.XXX.XXX#53(XXX.XXX.XXX.XXX)
;; WHEN: Mon Feb 08 20:36:32 EET 2016
;; MSG SIZE  rcvd: 59
```

### CODE REVIEW

**Comment by rickmclean** [comment]
Thanks for the patch!

**Comment by rickmclean** [comment]
I forgot!! 
You can help us anytime you want, you're welcome to participate in this amazing journey. We are looking forward to see you again around here.

**Comment by zloster** [comment]
Thanks :+1:

**Comment by rickmclean** [comment]
You're welcome!
You can also subscribe to our new mail list:
thunderbit-dev+subscribe@googlegroups.com
Any idea you think that may help us you can share it here, we'll
appreciate it.
Regards

**Pull request merged**
